#!/usr/bin/env python3
"""
Reproducibility harness — proves that the same input, on the same version, yields
the same result, and records each run so a third party can re-run and compare.

    python3 verify.py            # write verification/records.json + verification/REPORT.md
    python3 verify.py --check    # exit nonzero if results are not reproducible

For every case it records the input, the recovered generator (class + parameters),
the residual, the score (verified + compression), a content hash, plus the commit
and a timestamp. The determinism check re-runs the whole corpus and confirms the
engine-result fields are byte-identical (timestamps and commit are metadata and
are excluded from that comparison).
"""
import os
import sys
import json
import time
import hashlib
import argparse
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from chiron import collapse  # noqa: E402

OUT = os.path.join(HERE, "verification")

CORPUS = [
    ("constant", "5 5 5 5 5 5"),
    ("arithmetic", "3 7 11 15 19 23 27"),
    ("geometric", "1 2 4 8 16 32 64"),
    ("polynomial_deg2", "0 1 4 9 16 25 36 49"),
    ("polynomial_deg3", "0 1 8 27 64 125 216"),
    ("fibonacci", "0 1 1 2 3 5 8 13 21 34"),
    ("lucas", "2 1 3 4 7 11 18 29 47"),
    ("pell", "0 1 2 5 12 29 70 169"),
    ("catalan", "1 1 2 5 14 42 132 429 1430 4862 16796 58786 208012 742900"),
    ("factorial", "1 1 2 6 24 120 720 5040 40320 362880 3628800"),
    ("primes_abstains", "2 3 5 7 11 13 17 19 23 29"),
    ("partitions_abstains", "1 1 2 3 5 7 11 15 22 30"),
]


def _nums(s):
    from fractions import Fraction
    return [int(x) if float(x).is_integer() else Fraction(x) for x in s.split()]


def _result(label, raw):
    inv = collapse(_nums(raw))
    d = inv.to_dict()
    # the engine-result fields only — deterministic, no metadata
    return {
        "label": label,
        "input": raw,
        "generator": {"model_class": d["model_class"], "params": d["params"]},
        "verified": d["verified"],
        "residual": d["residual"],
        "score": {"model_bits": d["model_bits"], "surface_bits": d["surface_bits"],
                  "compression_ratio": d["compression_ratio"]},
        "fingerprint": d["generator_fingerprint"],
    }


def run_corpus():
    return [_result(label, raw) for label, raw in CORPUS]


def _digest(records):
    return hashlib.sha256(
        json.dumps(records, sort_keys=True, default=str).encode()).hexdigest()


def _commit():
    try:
        return subprocess.run(["git", "rev-parse", "HEAD"], cwd=HERE,
                              capture_output=True, text=True, timeout=10).stdout.strip() or "unknown"
    except Exception:
        return "unknown"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit nonzero if not reproducible")
    args = ap.parse_args()

    records = run_corpus()
    again = run_corpus()
    reproducible = _digest(records) == _digest(again)

    if args.check:
        print("reproducible:" , reproducible, "  digest:", _digest(records)[:16])
        return 0 if reproducible else 1

    os.makedirs(OUT, exist_ok=True)
    manifest = {
        "system": "CHIRON",
        "commit": _commit(),
        "generated_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "corpus_size": len(records),
        "result_digest": _digest(records),
        "reproducible_same_version": reproducible,
        "records": records,
    }
    with open(os.path.join(OUT, "records.json"), "w") as f:
        json.dump(manifest, f, indent=2, default=str)

    recovered = sum(1 for r in records if r["verified"])
    abstained = len(records) - recovered
    md = [
        "# Verification report",
        "",
        "Generated by `python3 verify.py`. Re-run it and compare `result_digest`:",
        "if the digest matches, every recovered generator, residual, and score is "
        "byte-identical to this run.",
        "",
        "| field | value |",
        "|---|---|",
        "| commit | `%s` |" % manifest["commit"],
        "| generated (UTC) | %s |" % manifest["generated_utc"],
        "| corpus size | %d |" % manifest["corpus_size"],
        "| recovered (verified) | %d |" % recovered,
        "| abstained (honest) | %d |" % abstained,
        "| reproducible (same version) | **%s** |" % reproducible,
        "| result digest | `%s` |" % manifest["result_digest"][:32],
        "",
        "## Per-case results",
        "",
        "| case | input | generator | verified | compression |",
        "|---|---|---|---|---|",
    ]
    for r in records:
        md.append("| %s | `%s` | `%s` | %s | %sx |" % (
            r["label"], r["input"], r["generator"]["model_class"],
            r["verified"], r["score"]["compression_ratio"]))
    md += ["", "Full machine-readable records, including parameters and fingerprints, "
           "are in [`records.json`](records.json)."]
    with open(os.path.join(OUT, "REPORT.md"), "w") as f:
        f.write("\n".join(md) + "\n")
    print("wrote verification/records.json and verification/REPORT.md  "
          "(reproducible=%s, %d/%d recovered)" % (reproducible, recovered, len(records)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
