#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Jacob Iannotti
"""
build_encyclopedia — project ../docs/ENCYCLOPEDIA.md from manifest.json +
lexicon.json, so the reference can never drift from the code.

The manifest is the machine-readable truth about every runnable script (what
it is, what it imports, whether its gates ran green, what certificate it left);
the lexicon carries the human vocabulary (title + the three lenses). This
script folds both into one readable reference, the same way build_monolith.py
folds the source: generated, never hand-edited.

    python3 build_encyclopedia.py          # (re)write ../docs/ENCYCLOPEDIA.md

Regenerate after build_manifest.py --run. stdlib only, deterministic given
its inputs.
"""
from __future__ import annotations

import json
import os

_HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(_HERE, os.pardir, "docs", "ENCYCLOPEDIA.md"))

ROLE_TITLES = [
    ("certifying", "Certifying engines — they leave signed, falsifiable certificates"),
    ("benchmark", "Benchmarks — measured against external baselines"),
    ("builder", "Builders — they generate artifacts from sources of truth"),
    ("server", "Servers — the dashboard's live services"),
    ("test", "Test batteries"),
]


def _entry(e: dict) -> str:
    lines = [f"### `{e['script']}`" + (f" — {e['title']}" if e.get("title") else "")]
    if e.get("purpose"):
        lines.append(f"\n{e['purpose']}")
    lens = e.get("lens") or {}
    for key, label in (("math", "Mathematically"), ("prog", "Programmatically"),
                       ("concept", "Conceptually")):
        if lens.get(key):
            lines.append(f"\n- **{label}:** {lens[key]}")
    facts = []
    if e.get("roles"):
        facts.append("roles: " + ", ".join(e["roles"]))
    facts.append("selftest: " + ("yes" if e.get("has_selftest") else "no"))
    facts.append("deps: " + (", ".join(e["dependencies"]) if e.get("dependencies") else "stdlib only"))
    if e.get("imports"):
        facts.append("imports: " + ", ".join(f"`{i}`" for i in e["imports"]))
    if e.get("imported_by"):
        facts.append("imported by: " + ", ".join(f"`{i}`" for i in e["imported_by"]))
    lines.append("\n- **Facts:** " + " · ".join(facts))
    art = e.get("artifact")
    if art:
        if art.get("what_was_discovered"):
            lines.append(f"- **Last certificate found:** {art['what_was_discovered']}")
        if art.get("what_would_falsify"):
            lines.append(f"- **What would falsify it:** {art['what_would_falsify']}")
    run = e.get("last_run")
    if run and run.get("exit_code") is not None:
        verdict = "green" if run["exit_code"] == 0 else f"RED (exit {run['exit_code']})"
        lines.append(f"- **Last gate run:** {verdict} in {run.get('runtime_ms', '?')} ms")
    lines.append(f"- **Path:** `Chiron/{e['path']}`" if not e["path"].startswith("..")
                 else f"- **Path:** `{e['path']}`")
    return "\n".join(lines)


def build() -> str:
    with open(os.path.join(_HERE, "manifest.json"), encoding="utf-8") as f:
        man = json.load(f)
    scripts = sorted(man["scripts"], key=lambda e: e["script"])
    s = man["summary"]

    parts = [
        "# The Chiron Encyclopedia — every module, from the manifest",
        "",
        "**@generated by `Chiron/build_encyclopedia.py` — do not hand-edit.**",
        "Regenerate: `python3 Chiron/build_manifest.py --run && python3 Chiron/build_encyclopedia.py`.",
        "The [manifest](../Chiron/manifest.json) is the machine truth this page projects;",
        "the [DICTIONARY](DICTIONARY.md) defines the vocabulary; the [SOP](SOP.md) says how to operate it all.",
        "",
        f"**State at generation:** {s['runnable_scripts']} runnable scripts · "
        f"{s['with_selftest']} carry selftest gates · {s['stdlib_only']} stdlib-only · "
        f"{s['with_spdx_header']} licensed · {s.get('internal_edges', '?')} internal import edges · "
        f"generated {man.get('generated_utc', '?')} ({man.get('mode', '?')} mode).",
        "",
        "## Index by role",
        "",
    ]
    for role, title in ROLE_TITLES:
        members = [e["script"] for e in scripts if role in (e.get("roles") or [])]
        if members:
            parts.append(f"- **{title}:** " + ", ".join(f"`{m}`" for m in members))
    hubs = sorted(scripts, key=lambda e: -len(e.get("imported_by") or []))[:5]
    parts.append("- **Most depended-upon (the spine's hubs):** " +
                 ", ".join(f"`{e['script']}` ({len(e['imported_by'])} dependents)"
                           for e in hubs if e.get("imported_by")))
    parts.append("")
    parts.append("## The modules, A–Z")
    parts.append("")
    for e in scripts:
        parts.append(_entry(e))
        parts.append("")
    return "\n".join(parts)


def main() -> int:
    text = build()
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(text)
    n = text.count("### `")
    print(f"[encyclopedia] {n} module entries -> {os.path.relpath(OUT, _HERE)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
