#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Jacob Iannotti
"""
build_monolith.py — fold ALL of Chiron's runnable code into one file.

Reads every Chiron/*.py, embeds its byte-identical source (base64) into a single
generated `chiron_monolith.py`, and wraps it in a small loader + dispatcher so that:

  * any cross-import (`import chiron`, `import semic`, `import legal_corpus`, ...)
    resolves to the EMBEDDED copy via a sys.meta_path finder, and
  * any module's command line runs with:  python3 chiron_monolith.py <module> [args...]

Each embedded source is asserted byte-identical to the original at build time, so the
monolith is a lossless fold of the spine, not a rewrite. Data files and each module's
self-source scan resolve against the sibling Chiron/ tree when present (the in-repo case).

    python3 build_monolith.py            # (re)generate chiron_monolith.py
    python3 build_monolith.py --verify   # generate, then run the engine battery through it
"""
import os
import sys
import base64
import argparse
import subprocess

_HERE = os.path.dirname(os.path.abspath(__file__))          # the Chiron Monolith folder
CHIRON = os.path.normpath(os.path.join(_HERE, os.pardir, "Chiron"))   # the sibling spine to fold
OUT = os.path.join(_HERE, "chiron_monolith.py")

# [2026-07-16] Cross-package spine dependencies, folded in so the monolith is truly
# standalone. cert_engine (JDICert) and candor (Candor) are imported by Chiron/*.py
# (density_emotion, axioms, holographic, candor_bridge, judgment, ...) but live outside
# Chiron/ — without them the "one file" silently required the vault beside it. Same
# byte-identical embedding and round-trip assertion as the spine. cert_engine needs
# numpy at import time; that is the fold's one external dependency and is disclosed.
EXTRA_SPINE = {
    "cert_engine": os.path.normpath(os.path.join(_HERE, os.pardir, "JDICert", "cert_engine.py")),
    "candor": os.path.normpath(os.path.join(_HERE, os.pardir, "Candor", "candor.py")),
}

# Runtime files copied next to the monolith so the folder is self-contained — it can serve the
# dashboard and run standalone even with no sibling Chiron/ directory present.
_BUNDLE = ["dashboard.html", "parameters.json",
           "lexicon.json", "manifest.json"]

# The generated monolith's static head: SPDX + docstring + loader + dispatcher.
# Written with no backslash escapes so it round-trips cleanly into the output file.
HEAD = r'''#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Jacob Iannotti. Licensed under the Apache License, Version 2.0. See LICENSE.
# @generated by "Chiron Monolith/build_monolith.py" — DO NOT EDIT THIS FILE.
# The Chiron/*.py modules are the single source of truth; edit them and regenerate:
#     python3 "Chiron Monolith/build_monolith.py"
"""
chiron_monolith.py — ALL of Chiron, folded into ONE file. (generated; do not hand-edit)

Every Chiron module is embedded below as byte-identical base64 source. A sys.meta_path
finder makes `import <name>` resolve to the embedded copy, so the cross-imports between
modules work even with no Chiron/*.py files alongside. Each module's __file__ (used for
self-source scans and _HERE-relative data) points at the sibling Chiron/ directory when
it exists — the normal in-repo case — so behaviour is identical to running the originals.

    python3 chiron_monolith.py serve                 # open the operator dashboard on :8765
    python3 chiron_monolith.py --list                # list every embedded module (and plugins)
    python3 chiron_monolith.py <module> [args...]     # run a module's command line
    python3 chiron_monolith.py semic selftest         # -> 56/56 gates
    python3 chiron_monolith.py chiron selftest        # -> CHIRON GREEN
    python3 chiron_monolith.py --selftest             # FULL sweep: every selftest-bearing module
    python3 chiron_monolith.py --smoke                # quick: just the core-engine battery

Plugins (prototype): drop <name>.py into a plugins/ folder next to this file and
`python3 chiron_monolith.py <name>` runs it; it may import any embedded module.
Embedded modules ALWAYS win over a plugin with the same name — a plugin can add
to the runtime, never replace the certified spine. The --selftest sweep covers
ONLY embedded modules, so its coverage claim is the fold's, not a plugin's.

Regenerate with build_monolith.py. The embedded sources are a lossless fold of the spine —
byte-identical to Chiron/*.py — so the fold runs exactly the gates the full build runs.
"""
import sys
import os
import base64
import importlib.abc
import importlib.machinery
import importlib.util

_HERE = os.path.dirname(os.path.abspath(__file__))
_CHIRON = os.path.normpath(os.path.join(_HERE, os.pardir, "Chiron"))
_PLUGIN_DIR = os.path.join(_HERE, "plugins")


def _decode(name):
    return base64.b64decode(_SOURCES[name]).decode("utf-8")


def _register_source(name, filename):
    """Make the embedded source visible to inspect.getsource / traceback, keyed by the
    module's __file__ — so a folded module that scans its OWN source (e.g. a license-header
    gate that calls inspect.getsource(sys.modules[__name__])) works even when no matching
    .py exists on disk. This is what lets the fold be genuinely standalone, not just importable."""
    import linecache
    src = _decode(name)
    lines = src.splitlines(keepends=True)
    linecache.cache[filename] = (len(src), None, lines, filename)


def _plugin_path(name):
    """plugins/<name>.py — but ONLY for names that are not embedded. The
    embedded spine always wins, so a plugin can never shadow (and thereby
    silently replace) a certified module."""
    if name in _SOURCES or not name.isidentifier():
        return None
    p = os.path.join(_PLUGIN_DIR, name + ".py")
    return p if os.path.isfile(p) else None


def _plugin_names():
    if not os.path.isdir(_PLUGIN_DIR):
        return []
    return sorted(f[:-3] for f in os.listdir(_PLUGIN_DIR)
                  if f.endswith(".py") and _plugin_path(f[:-3]))


_EXTRA_REAL = {
    "cert_engine": os.path.normpath(os.path.join(_HERE, os.pardir, "JDICert", "cert_engine.py")),
    "candor": os.path.normpath(os.path.join(_HERE, os.pardir, "Candor", "candor.py")),
}


def _module_file(name):
    """__file__ for an embedded module: the real source when present (so self-source
    scans and _HERE-relative data resolve), else a virtual local path. Cross-package
    spine modules (cert_engine, candor) resolve to their own packages, not Chiron/."""
    real = _EXTRA_REAL.get(name, os.path.join(_CHIRON, name + ".py"))
    return real if os.path.isfile(real) else os.path.join(_HERE, name + ".py")


class _Loader(importlib.abc.Loader):
    def __init__(self, name):
        self._name = name

    def create_module(self, spec):
        return None

    def exec_module(self, module):
        module.__file__ = _module_file(self._name)
        _register_source(self._name, module.__file__)
        exec(compile(_decode(self._name), module.__file__, "exec"), module.__dict__)


class _Finder(importlib.abc.MetaPathFinder):
    def find_spec(self, fullname, path=None, target=None):
        if fullname in _SOURCES:
            return importlib.machinery.ModuleSpec(fullname, _Loader(fullname))
        plug = _plugin_path(fullname)                 # additive only; never shadows
        if plug:
            return importlib.util.spec_from_file_location(fullname, plug)
        return None


def _install():
    if not any(isinstance(f, _Finder) for f in sys.meta_path):
        sys.meta_path.insert(0, _Finder())


def run_module(name, argv):
    """Execute an embedded module's command line as if it were __main__.

    The module is registered in sys.modules as both "__main__" and its own name and
    given a real module object, because the spine self-references through
    sys.modules[__name__] (e.g. `veritas = sys.modules[__name__]`) and scans its own
    source via inspect.getsource(sys.modules[__name__]); both must resolve to the
    running module (and its real Chiron/<name>.py source), not to this launcher."""
    import types
    _install()
    plug = None
    if name not in _SOURCES:
        plug = _plugin_path(name)
        if plug is None:
            print("unknown module:", name,
                  "(try --list; plugins live in plugins/)", file=sys.stderr)
            return 2
    mod = types.ModuleType("__main__")
    mod.__name__ = "__main__"
    mod.__file__ = plug if plug else _module_file(name)
    mod.__package__ = None
    if not plug:
        _register_source(name, mod.__file__)   # self-source scans work standalone
    saved_argv = list(sys.argv)
    saved_main = sys.modules.get("__main__")
    saved_named = sys.modules.get(name)
    sys.argv = [name + ".py"] + list(argv)
    sys.modules["__main__"] = mod
    sys.modules[name] = mod
    try:
        src = open(plug, encoding="utf-8").read() if plug else _decode(name)
        exec(compile(src, mod.__file__, "exec"), mod.__dict__)
        return 0
    except SystemExit as exc:
        if isinstance(exc.code, int):
            return exc.code
        return 1 if exc.code else 0
    finally:
        sys.argv = saved_argv
        if saved_main is not None:
            sys.modules["__main__"] = saved_main
        else:
            sys.modules.pop("__main__", None)
        if saved_named is not None:
            sys.modules[name] = saved_named
        else:
            sys.modules.pop(name, None)


# Servers and corpus-mutating tools are not auto-run in a sweep (identical to the full
# build's build_manifest.NO_AUTORUN), so the fold's coverage matches the spine's exactly.
_NO_AUTORUN = {"assistant_server", "console_server", "chiron_grow", "president_grow",
               "grow_control", "grow_clean", "build_manifest", "ingest_pdf",
               # cross-package libraries folded in [2026-07-16] for import resolution
               # (Chiron modules do `import candor` / `import cert_engine`); they are
               # exercised THROUGH the spine (candor's over-assertion gate, the JDICert
               # 280-test suite), not via their own CLI, so the sweep does not auto-run them.
               "candor"}
_SMOKE = ["semic", "chiron", "density_emotion", "semic_energy", "epistemic"]


def _run_self(name):
    """Run one embedded module's selftest IN-PROCESS, capturing its output. run_module
    registers/restores sys.modules around each run, so the whole sweep needs only one parse
    of the fold (fast). Falls back from the positional `selftest` to the `--selftest` flag,
    exactly as the full build's runner does, so a module's invocation style never counts as a fail."""
    import io
    import contextlib
    buf = io.StringIO()
    try:
        with contextlib.redirect_stdout(buf), contextlib.redirect_stderr(buf):
            rc = run_module(name, ["selftest"])
            if rc == 2:
                rc = run_module(name, ["--selftest"])
        out = [ln for ln in buf.getvalue().strip().splitlines() if ln.strip()]
        return rc == 0, (out[-1] if out else "")[:70]
    except Exception as exc:
        return False, repr(exc)[:70]


def _selftest(full=True):
    """full=True sweeps EVERY selftest-bearing embedded module (the same set the full build
    runs); full=False runs only the core-engine smoke battery. Plugins are DELIBERATELY
    excluded: the sweep's green is a claim about the certified fold, never about
    external files someone dropped alongside it."""
    if full:
        names = sorted(n for n in _SOURCES
                       if "selftest" in _decode(n) and n not in _NO_AUTORUN)
        title = "full sweep — every selftest-bearing module, through the fold"
    else:
        names = [n for n in _SMOKE if n in _SOURCES]
        title = "smoke battery — the core engines, through the fold"
    rows = [(n, *_run_self(n)) for n in names]
    print("chiron_monolith self-test (%s)" % title)
    for name, ok, tail in rows:
        print("  [%s] %-18s %s" % ("PASS" if ok else "FAIL", name, tail))
    passed = sum(1 for _, ok, _ in rows if ok)
    print("  %d/%d modules green through the fold "
          "(same coverage as the full build's manifest)" % (passed, len(rows)))
    return passed == len(rows)


def main(argv=None):
    args = list(sys.argv[1:] if argv is None else argv)
    if not args or args[0] in ("-h", "--help"):
        print(__doc__)
        return 0
    if args[0] == "--list":
        for key in sorted(_SOURCES):
            print(key)
        plugins = _plugin_names()
        for key in plugins:
            print(key, "[plugin — external file, not part of the certified fold]")
        print()
        print("%d modules embedded%s." % (len(_SOURCES),
              ", %d plugin(s) alongside" % len(plugins) if plugins else ""))
        return 0
    if args[0] == "--selftest":
        return 0 if _selftest(full=True) else 1
    if args[0] == "--smoke":
        return 0 if _selftest(full=False) else 1
    if args[0] in ("serve", "dashboard", "console"):
        # Open the operator console from the one file. The engine finds dashboard.html next to
        # its __file__: the sibling Chiron/ in-repo, or this folder when run standalone (the
        # dashboard + data are bundled here), so the console works either way.
        return run_module("chiron", ["serve"] + args[1:])
    return run_module(args[0], args[1:])


'''

TAIL = '''
if __name__ == "__main__":
    sys.exit(main())
'''


def build():
    files = sorted(f for f in os.listdir(CHIRON) if f.endswith(".py"))
    entries = []
    total = 0
    for fname in files:
        name = fname[:-3]
        raw = open(os.path.join(CHIRON, fname), "rb").read()
        b64 = base64.b64encode(raw).decode("ascii")
        assert base64.b64decode(b64) == raw, "round-trip failed: " + fname
        entries.append((name, b64))
        total += len(raw)
    for name, path in sorted(EXTRA_SPINE.items()):     # cross-package spine deps
        assert name not in {e[0] for e in entries}, "name collision: " + name
        assert os.path.isfile(path), "missing spine dependency: " + path
        raw = open(path, "rb").read()
        b64 = base64.b64encode(raw).decode("ascii")
        assert base64.b64decode(b64) == raw, "round-trip failed: " + name
        entries.append((name, b64))
        total += len(raw)
    with open(OUT, "w", encoding="utf-8") as out:
        out.write(HEAD)
        out.write("_SOURCES = {}\n")
        for name, b64 in entries:
            out.write("_SOURCES[%r] = (\n" % name)
            for i in range(0, len(b64), 120):
                out.write("    %r\n" % b64[i:i + 120])
            out.write(")\n")
        out.write(TAIL)
    bundled = _bundle()
    return entries, total, bundled


def _bundle():
    """Copy the runtime UI + data next to the monolith so the folder is self-contained: it can
    serve the dashboard and run standalone even with no sibling Chiron/ directory present."""
    import shutil
    copied = []
    for fn in _BUNDLE:
        src = os.path.join(CHIRON, fn)
        if os.path.isfile(src):
            shutil.copy2(src, os.path.join(_HERE, fn))
            copied.append(fn)
    seed = os.path.join(CHIRON, "chiron_memory_clean.json")
    if os.path.isfile(seed):                       # a clean Congress for a standalone run
        shutil.copy2(seed, os.path.join(_HERE, "chiron_memory.json"))
        copied.append("chiron_memory.json")
    return copied


def main():
    ap = argparse.ArgumentParser(description="Fold all of Chiron into one file.")
    ap.add_argument("--verify", action="store_true",
                    help="after generating, run the engine battery through the monolith")
    args = ap.parse_args()
    entries, total, bundled = build()
    out_bytes = os.path.getsize(OUT)
    print("[monolith] embedded %d modules (%d source bytes) -> %s (%d bytes)"
          % (len(entries), total, os.path.relpath(OUT, _HERE), out_bytes))
    print("[monolith] bundled %d runtime files for a self-contained dashboard: %s"
          % (len(bundled), ", ".join(bundled)))
    if args.verify:
        print("[monolith] verifying via --selftest ...")
        rc = subprocess.run([sys.executable, OUT, "--selftest"]).returncode
        return rc
    return 0


if __name__ == "__main__":
    sys.exit(main())
