#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Jacob Iannotti
"""Turn results.jsonl from the rank-2 sweep into a readable report.

Pure stdlib -- no PARI, no Arb -- so it runs anywhere and can be re-run after
an interrupted sweep. Writes RESULTS.md next to it.
"""
from __future__ import annotations

import json
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "results.jsonl")
OUT = os.path.join(HERE, "RESULTS.md")


def main() -> None:
    if not os.path.exists(SRC):
        print("no results.jsonl yet")
        return
    rows, seen = [], set()
    for line in open(SRC):
        try:
            r = json.loads(line)
        except Exception:
            continue
        if r["N"] in seen:
            continue
        seen.add(r["N"])
        rows.append(r)
    rows.sort(key=lambda r: r["N"])

    consistent = [r for r in rows if r["verdict"] == "CONSISTENT"]
    refuted = [r for r in rows if "REFUTED" in r["verdict"]]
    unsat = [r for r in rows if r["verdict"] == "UNSATURATED"]
    other = [r for r in rows if r not in consistent + refuted + unsat]

    widths = [r["sha_hi"] - r["sha_lo"] for r in rows]
    squares = sorted({r["square"] for r in consistent if r["square"]})

    L = []
    L.append("<!-- SPDX-License-Identifier: Apache-2.0 -->")
    L.append("<!-- Copyright 2026 Jacob Iannotti -->")
    L.append("")
    L.append("# Rank-2 BSD falsification sweep — results")
    L.append("")
    L.append("Generated by `summarize_results.py` from `results.jsonl`.")
    L.append("Method and caveats: see `README.md`. Nothing here is VERIFIED.")
    L.append("")
    L.append("## Headline")
    L.append("")
    L.append(f"- curves certified end-to-end: **{len(rows)}**")
    L.append(f"- distinct conductors: **{len(seen)}**, "
             f"range **{min(r['N'] for r in rows)}–{max(r['N'] for r in rows)}**")
    L.append(f"- **REFUTATIONS of the strong BSD formula: {len(refuted)}**")
    L.append(f"- CONSISTENT: {len(consistent)} · unsaturated: {len(unsat)} "
             f"· inconclusive: {len(other)}")
    L.append(f"- enclosed squares observed: {squares}")
    L.append(f"- widest `Sha_an` ball: {max(widths):.3e}; "
             f"tightest: {min(widths):.3e}")
    L.append("")
    L.append("Every row has: analytic rank proved exactly 2 (exact modular "
             "symbol `L(1)=0`, root number +1, Arb ball for `L''(1)/2` "
             "excluding zero), Mordell–Weil basis **proved saturated**, and "
             "an interval for the full BSD quotient.")
    L.append("")
    L.append("A ball containing no integer, or a non-square integer, would "
             "refute strong BSD for that curve. Both are verdicts the "
             "round-to-nearest procedure cannot return. None occurred.")
    L.append("")
    if refuted:
        L.append("## REFUTATIONS — inspect these before believing them")
        L.append("")
        L.append("| curve | N | Reg | Sha_an | ints |")
        L.append("|---|---|---|---|---|")
        for r in refuted:
            L.append(f"| `{r['ainvs']}` | {r['N']} | {r['reg']:.5f} | "
                     f"[{r['sha_lo']:.6f}, {r['sha_hi']:.6f}] | "
                     f"{r['n_integers']} |")
        L.append("")
        L.append("A refutation is far more likely to be a bug than a "
                 "counterexample to BSD. Check the period convention, the "
                 "Tamagawa product, and the saturation certificate first.")
        L.append("")
    L.append("## All certified curves")
    L.append("")
    L.append("| curve | N | μ | m ≤ | Reg | tors | ∏c_p | `Sha_an` | verdict |")
    L.append("|---|---|---|---|---|---|---|---|---|")
    for r in rows:
        mid = 0.5 * (r["sha_lo"] + r["sha_hi"])
        rad = 0.5 * (r["sha_hi"] - r["sha_lo"])
        L.append(f"| `{r['ainvs']}` | {r['N']} | {r['mu']:.4f} | "
                 f"{int(math.floor(r['m_bound']))} | {r['reg']:.5f} | "
                 f"{r['torsion']} | {r['tamagawa']} | "
                 f"{mid:.5f} ± {rad:.1e} | {r['verdict']} |")
    L.append("")
    if len(squares) <= 1:
        L.append("## Methodological limitation: every answer is the same")
        L.append("")
        L.append(f"Every certified curve enclosed the same square, {squares}. "
                 "That is expected — non-trivial Sha is rare at rank 2 in this "
                 "conductor range — but it means **this sweep does not "
                 "exercise the non-trivial-Sha path at all**. A bug that "
                 "forced the quotient to 1 (a dropped Tamagawa factor, a "
                 "period off by a constant, a regulator scaled wrong) would "
                 "produce exactly this table and nothing here would catch it.")
        L.append("")
        L.append("What does constrain that: the same period/torsion/Tamagawa "
                 "code path reproduces `Sha_an = 4` for 571.b1 in "
                 "`../exact_rank0_sha/`, and the unsaturated controls return "
                 "1/4 and 1/9 rather than 1 — so the pipeline demonstrably "
                 "can emit values other than 1.")
        L.append("")
        L.append("**The missing test was attempted and not found.** "
                 "`hunt_nontrivial_sha.py` screens with PARI's own floating "
                 "quotient (a search heuristic, never evidence) and hands any "
                 "candidate far from 1 to the exact certificate. It screened "
                 "**1,443 rank-2 curves** over an a-invariant box of radius 26 "
                 "with conductors to 400,000 and found **none** with "
                 "`Sha_an > 1.6`.")
        L.append("")
        L.append("That null result is only worth stating because the screen "
                 "was checked against its own blind spot: fed deliberately "
                 "unsaturated bases for 389.a1 it returns 1, 1/4 and 1/9 for "
                 "index 1, 2 and 3, so it is not structurally pinned to 1. "
                 "Non-trivial Sha at rank 2 is simply rare in this range. "
                 "Certifying such a curve remains the strongest missing test; "
                 "it will need a targeted source of candidates rather than a "
                 "box scan.")
        L.append("")
    L.append("## What a CONSISTENT row does not mean")
    L.append("")
    L.append("It does **not** mean `#Sha` equals the enclosed square. The "
             "enclosure is equally satisfied by a nearby non-integer, and "
             "integrality of the quotient is exactly what BSD asserts and "
             "what remains unproved in rank 2. The one-way content is real "
             "though: had a ball missed every integer, that would have been "
             "a refutation.")
    open(OUT, "w").write("\n".join(L) + "\n")
    print(f"wrote {OUT}")
    print(f"  {len(rows)} curves, {len(refuted)} refutations, "
          f"conductors {min(r['N'] for r in rows)}-{max(r['N'] for r in rows)}")


if __name__ == "__main__":
    main()
