#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Jacob Iannotti. See LICENSE.
"""Regenerate docs/STATE.json — the machine-readable state of this checkout.

Written so a status record can never drift from the repository: every field is
read at run time from git, the package index, the manifest, or the toolchain.
Nothing here is typed in by hand, which is the property that makes it worth
trusting.

    python3 ci/state.py            # write docs/STATE.json
    python3 ci/state.py --print    # write and print
    python3 ci/state.py --check    # non-zero if the file on disk is stale
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
from datetime import datetime, timezone

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "STATE.json")
SCHEMA = "chiron.state/1"


def _sh(command: str, timeout: int = 60) -> str:
    try:
        result = subprocess.run(command, shell=True, capture_output=True,
                                text=True, cwd=ROOT, timeout=timeout)
        return result.stdout.strip()
    except Exception:
        return ""


def _pypi_version(package: str) -> str:
    """The live published version, or "unknown" offline. Never a cached guess:
    a state file that invents a version is worse than one that admits it could
    not look."""
    raw = _sh("curl -sS --max-time 20 https://pypi.org/pypi/%s/json" % package, 30)
    try:
        return json.loads(raw)["info"]["version"]
    except Exception:
        return "unknown (no network at generation time)"


def collect() -> dict:
    manifest = os.path.join(ROOT, "Chiron", "manifest.json")
    modules = 0
    if os.path.isfile(manifest):
        try:
            modules = len(json.load(open(manifest))["scripts"])
        except Exception:
            modules = 0

    tools: list = []
    try:
        sys.path.insert(0, os.path.join(ROOT, "Chiron"))
        import mcp_server
        tools = [t["name"] for t in mcp_server.TOOLS]
    except Exception:
        pass

    return {
        "schema": SCHEMA,
        "generated_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "note": "Generated by ci/state.py. Every field is read from the "
                "repository or the network at run time; nothing is hand-typed.",
        "git": {
            "branch": _sh("git branch --show-current"),
            "head": _sh("git rev-parse HEAD"),
            "remote_main": _sh("git ls-remote origin refs/heads/main | cut -f1", 45),
            "uncommitted_files": len([l for l in _sh("git status --porcelain").splitlines() if l]),
            "ahead_of_origin_main": _sh("git rev-list --count origin/main..HEAD"),
        },
        "published": {
            "pypi_package": "primus-intelligence",
            "pypi_version": _pypi_version("primus-intelligence"),
            "github": "https://github.com/jiannotti5040/chiron",
        },
        "counts": {
            "tracked_files": int(_sh("git ls-files | wc -l") or 0),
            "chiron_modules": modules,
            "mcp_tools": len(tools),
        },
        "mcp_tools": tools,
        "toolchain": {
            "python": _sh("python3 --version"),
            "swift": _sh("swift --version 2>/dev/null | head -1"),
            "xcode": _sh("xcodebuild -version 2>/dev/null | head -1"),
        },
    }


def main(argv=None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    state = collect()

    if "--check" in argv:
        try:
            on_disk = json.load(open(OUT))
        except Exception:
            print("state: docs/STATE.json missing or unreadable")
            return 1
        # Compare only what the REPOSITORY determines. An allowlist, not a
        # denylist, so a new environment-derived field cannot silently make
        # this gate unsatisfiable again.
        #
        # Everything else in the file is a snapshot of wherever it was
        # generated, and comparing it for equality is incoherent:
        #   git        — branch/HEAD/uncommitted change on the very next commit,
        #                so the file went stale the instant it was committed.
        #                This is why --check was perpetually red and wired into
        #                no workflow.
        #   published  — pypi_version is fetched from the network, so every
        #                release to PyPI would turn CI red until someone
        #                remembered to regenerate a file.
        #   toolchain  — the local Python/Swift/Xcode; a Linux runner has no
        #                Xcode at all, so this can never match in CI.
        #
        # What is left is exactly the class of thing that can be stale *and
        # wrong*: the counts and the tool surface a reader is told to expect.
        CHECKED = {"schema", "counts", "mcp_tools"}
        a = {k: v for k, v in state.items() if k in CHECKED}
        b = {k: v for k, v in on_disk.items() if k in CHECKED}
        if a != b:
            print("state: docs/STATE.json is stale; run python3 ci/state.py")
            return 1
        print("state: docs/STATE.json matches the checkout")
        return 0

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        json.dump(state, fh, indent=2)
        fh.write("\n")
    print("state: wrote %s" % os.path.relpath(OUT, ROOT))
    if "--print" in argv:
        print(json.dumps(state, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
